[package]
name = "rustyml"
version = "0.10.0"
edition = "2024"
rust-version = "1.85.0"
authors = ["SomeB1oody <stanyin64@gmail.com>"]
description = "A high-performance machine learning & deep learning library in pure Rust, offering ML algorithms and neural network support."
license = "MIT"
readme = "README.md"
keywords = ["machine_learning", "ML", "deep_learning", "neural_network", "AI"]
repository = "https://github.com/SomeB1oody/RustyML"
documentation = "https://docs.rs/crate/rustyml"
categories = ["mathematics", "science", "algorithms"]

[features]
default = ["machine_learning", "neural_network"]
dataset = ["dep:ndarray"]
machine_learning = ["math", "dep:ndarray", "dep:rayon", "dep:ahash", "dep:ndarray-rand", "dep:indicatif", "dep:serde", "dep:serde_json", "dep:rand"]
neural_network = ["dep:ndarray", "dep:rayon", "dep:ndarray-rand", "dep:rand", "dep:indicatif", "dep:serde", "dep:serde_json"]
utility = ["math", "dep:ndarray", "dep:rand", "dep:nalgebra", "dep:rayon", "dep:ahash", "dep:indicatif", "dep:serde", "dep:serde_json", "dep:ndarray-rand"]
math = ["dep:ndarray", "dep:ahash"]
metric = ["dep:ndarray", "dep:ahash"]
full = ["dataset", "machine_learning", "neural_network", "utility", "math", "metric"]

[dependencies]
ndarray = { version = "0.17.2", features = ["rayon", "serde"], optional = true }
rand = { version = "0.9.2", optional = true }
nalgebra = { version = "0.34.1", optional = true }
rayon = { version = "1.11.0", optional = true }
ndarray-rand = { version = "0.16.0", optional = true }
ahash = { version = "0.8.12", features = ["serde"], optional = true }
indicatif = { version = "0.18.3", optional = true }
serde = { version = "1.0.228", features = ["derive"], optional = true }
serde_json = { version = "1.0.149", optional = true}

[dev-dependencies]
approx = "0.5.1"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[package.metadata.docs.rs]
features = ["full"]
rustdoc-args = ["--cfg", "docsrs"]